os: linux
dist: xenial
language: r
pandoc_version: 2.9.1
install:
  # for rendering the PDFs
  - sudo apt-get install poppler-utils
  # for executing python based pandoc filters
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade setuptools
  # install python filters
  - pip3 install pandoc-latex-environment
  # packages needed for the template
  - tlmgr install xecjk filehook unicode-math ucharcat pagecolor babel-german ly1 mweights sourcecodepro sourcesanspro mdframed needspace fvextra footmisc footnotebackref background
  # packages only needed for some examples (that include packages via header-includes)
  - tlmgr install awesomebox fontawesome5
before_script:
  - cd examples
script:
  - sh build-examples.sh